const model_1 = {
  id: 1,
  description: "Arroz, integral, cozido",
  category: "Cereais e derivados",
  humidity_percentage: 70.1,
  energy_kcal: 124,
  energy_kj: 517,
  protein_g: 2.6,
  lipids_g: 1,
  cholesterol_mg: "NA",
  carbohydrate_g: 25.8,
  fiber_g: 2.7,
  ashes_g: 0.5,
  calcium_mg: 5,
  magnesium_mg: 59,
  manganese_mg: 0.63,
  phosphorus_mg: 106,
  iron_mg: 0.3,
  sodium_mg: 1,
  potassium_mg: 75,
  copper_mg: 0.02,
  zinc_mg: 0.7,
  retinol_mcg: "NA",
  re_mcg: "",
  rae_mcg: "",
  thiamine_mg: 0.08,
  riboflavin_mg: "Tr",
  pyridoxine_mg: 0.08,
  niacin_mg: "Tr",
  vitamin_c_mg: "",
  saturated_g: 0.3,
  monounsaturated_g: 0.4,
  polyunsaturated_g: 0.3,
  "12:0_g": "",
  "14:0_g": "Tr",
  "16:0_g": 0.25,
  "18:0_g": 0.02,
  "20:0_g": "Tr",
  "22:0_g": "Tr",
  "24:0_g": "Tr",
  "14:1_g": "",
  "16:1_g": "",
  "18:1_g": 0.36,
  "20:1_g": "Tr",
  "18:2 n-6_g": 0.31,
  "18:3 n-3_g": 0.01,
  "20:4_g": "",
  "20:5_g": "",
  "22:5_g": "Tr",
  "22:6_g": "",
  "18:1t_g": "",
  "18:2t_g": "",
  tryptophan_g: "",
  threonine_g: "",
  isoleucine_g: "",
  leucine_g: "",
  lysine_g: "",
  methionine_g: "",
  cystine_g: "",
  phenylalanine_g: "",
  tyrosine_g: "",
  valine_g: "",
  arginine_g: "",
  histidine_g: "",
  alanine_g: "",
  aspartic_g: "",
  glutamic_g: "",
  glycine_g: "",
  proline_g: "",
  serine_g: ""
};

const model_2 = {
  id: 303,
  description: "Merluza, filé, frito",
  category: "Pescados e frutos do mar",
  humidity_percentage: 63.5,
  energy_kcal: 192,
  energy_kj: 802,
  protein_g: 26.9,
  lipids_g: 8.5,
  cholesterol_mg: 109,
  carbohydrate_g: 0,
  fiber_g: "NA",
  ashes_g: 1.5,
  calcium_mg: 36,
  magnesium_mg: 38,
  manganese_mg: 0.02,
  phosphorus_mg: 279,
  iron_mg: 0.4,
  sodium_mg: 90,
  potassium_mg: 447,
  copper_mg: 0.03,
  zinc_mg: 0.6,
  retinol_mcg: "Tr",
  re_mcg: "Tr",
  rae_mcg: "Tr",
  thiamine_mg: 0.05,
  riboflavin_mg: "Tr",
  pyridoxine_mg: "Tr",
  niacin_mg: 0.77,
  vitamin_c_mg: "",
  saturated_g: "",
  monounsaturated_g: "",
  polyunsaturated_g: "",
  "12:0_g": "",
  "14:0_g": "",
  "16:0_g": "",
  "18:0_g": "",
  "20:0_g": "",
  "22:0_g": "",
  "24:0_g": "",
  "14:1_g": "",
  "16:1_g": "",
  "18:1_g": "",
  "20:1_g": "",
  "18:2 n-6_g": "",
  "18:3 n-3_g": "",
  "20:4_g": "",
  "20:5_g": "",
  "22:5_g": "",
  "22:6_g": "",
  "18:1t_g": "",
  "18:2t_g": "",
  tryptophan_g: "",
  threonine_g: "",
  isoleucine_g: "",
  leucine_g: "",
  lysine_g: "",
  methionine_g: "",
  cystine_g: "",
  phenylalanine_g: "",
  tyrosine_g: "",
  valine_g: "",
  arginine_g: "",
  histidine_g: "",
  alanine_g: "",
  aspartic_g: "",
  glutamic_g: "",
  glycine_g: "",
  proline_g: "",
  serine_g: ""
};

module.exports = {
  model_1,
  model_2
};
