import type { ValidUnit } from "./types";

export const unitsToSave = [
  { name: "moisture", unit: "%", namePt: "Umidade" },
  { name: "kcal", unit: "kcal", namePt: "Energia" },
  { name: "kJ", unit: "kj", namePt: "Energia" },
  { name: "protein", unit: "g", namePt: "Proteína" },
  { name: "lipids", unit: "g", namePt: "Lipídeos" },
  { name: "cholesterol", unit: "mg", namePt: "Colesterol" },
  { name: "carbohydrates", unit: "g", namePt: "Carboidrato" },
  { name: "dietaryFiber", unit: "g", namePt: "Fibra Alimentar" },
  { name: "ash", unit: "g", namePt: "Cinzas" },
  { name: "calcium", unit: "mg", namePt: "Cálcio" },
  { name: "magnesium", unit: "mg", namePt: "Magnésio" },
  { name: "manganese", unit: "mg", namePt: "Manganês" },
  { name: "phosphorus", unit: "mg", namePt: "Fósforo" },
  { name: "iron", unit: "mg", namePt: "Ferro" },
  { name: "sodium", unit: "mg", namePt: "Sódio" },
  { name: "potassium", unit: "mg", namePt: "Potássio" },
  { name: "copper", unit: "mg", namePt: "Cobre" },
  { name: "zinc", unit: "mg", namePt: "Zinco" },
  { name: "retinol", unit: "μg", namePt: "Retinol" },
  { name: "re", unit: "μg", namePt: "RE" },
  { name: "rae", unit: "μg", namePt: "RAE" },
  { name: "thiamin", unit: "mg", namePt: "Tiamina" },
  { name: "riboflavin", unit: "mg", namePt: "Riboflavina" },
  { name: "pyridoxine", unit: "mg", namePt: "Piridoxina" },
  { name: "niacin", unit: "mg", namePt: "Niacina" },
  { name: "vitaminC", unit: "mg", namePt: "Vitamina C" },

  { name: "tryptophan", unit: "g", namePt: "Triptofano" },
  { name: "threonine", unit: "g", namePt: "Treonina" },
  { name: "isoleucine", unit: "g", namePt: "Isoleucina" },
  { name: "leucine", unit: "g", namePt: "Leucina" },
  { name: "lysine", unit: "g", namePt: "Lisina" },
  { name: "methionine", unit: "g", namePt: "Metionina" },
  { name: "cystine", unit: "g", namePt: "Cistina" },
  { name: "phenylalanine", unit: "g", namePt: "Fenilalanina" },
  { name: "tyrosine", unit: "g", namePt: "Tirosina" },
  { name: "valine", unit: "g", namePt: "Valina" },
  { name: "arginine", unit: "g", namePt: "Arginina" },
  { name: "histidine", unit: "g", namePt: "Histidina" },
  { name: "alanine", unit: "g", namePt: "Alanina" },
  { name: "asparticAcid", unit: "g", namePt: "Ácido Aspártico" },
  { name: "glutamicAcid", unit: "g", namePt: "Ácido Glutâmico" },
  { name: "glycine", unit: "g", namePt: "Glicina" },
  { name: "proline", unit: "g", namePt: "Prolina" },
  { name: "serine", unit: "g", namePt: "Serina" },

  { name: "saturated", unit: "g", namePt: "Saturados" },
  { name: "monounsaturated", unit: "g", namePt: "Monoinsaturados" },
  { name: "polyunsaturated", unit: "g", namePt: "Poliinsaturados" },
  { name: "twelveZero", unit: "g", namePt: "12:0" },
  { name: "fourteenZero", unit: "g", namePt: "14:0" },
  { name: "fourteenOne", unit: "g", namePt: "14:1" },
  { name: "sixteenZero", unit: "g", namePt: "16:0" },
  { name: "sixteenOne", unit: "g", namePt: "16:1" },
  { name: "eighteenZero", unit: "g", namePt: "18:0" },
  { name: "eighteenOne", unit: "g", namePt: "18:1" },
  { name: "eighteenOneT", unit: "g", namePt: "18:1t" },
  { name: "eighteenTwoN6", unit: "g", namePt: "18:2n6" },
  { name: "eighteenTwoT", unit: "g", namePt: "18:2t" },
  { name: "eighteenThreeN3", unit: "g", namePt: "18:3n3" },
  { name: "twentyZero", unit: "g", namePt: "20:0" },
  { name: "twentyOne", unit: "g", namePt: "20:1" },
  { name: "twentyFour", unit: "g", namePt: "20:4" },
  { name: "twentyFive", unit: "g", namePt: "20:5" },
  { name: "twentyTwoZero", unit: "g", namePt: "22:0" },
  { name: "twentyTwoFive", unit: "g", namePt: "22:5" },
  { name: "twentyTwoSix", unit: "g", namePt: "22:6" },
  { name: "twentyFourZero", unit: "g", namePt: "24:0" },
] satisfies ValidUnit[];
