-- CreateTable
CREATE TABLE "fatty_acids" (
    "foodId" INTEGER NOT NULL,
    "saturated" DOUBLE PRECISION NOT NULL,
    "monounsaturated" DOUBLE PRECISION NOT NULL,
    "polyunsaturated" DOUBLE PRECISION NOT NULL,
    "12:0" DOUBLE PRECISION,
    "14:0" DOUBLE PRECISION,
    "14:1" DOUBLE PRECISION,
    "16:0" DOUBLE PRECISION,
    "16:1" DOUBLE PRECISION,
    "18:0" DOUBLE PRECISION,
    "18:1" DOUBLE PRECISION,
    "18:1t" DOUBLE PRECISION,
    "18:2n6" DOUBLE PRECISION,
    "18:2t" DOUBLE PRECISION,
    "18:3n3" DOUBLE PRECISION,
    "20:0" DOUBLE PRECISION,
    "20:1" DOUBLE PRECISION,
    "20:4" DOUBLE PRECISION,
    "20:5" DOUBLE PRECISION,
    "22:0" DOUBLE PRECISION,
    "22:5" DOUBLE PRECISION,
    "22:6" DOUBLE PRECISION,
    "24:0" DOUBLE PRECISION
);

-- CreateIndex
CREATE UNIQUE INDEX "fatty_acids_foodId_key" ON "fatty_acids"("foodId");

-- AddForeignKey
ALTER TABLE "fatty_acids" ADD CONSTRAINT "fatty_acids_foodId_fkey" FOREIGN KEY ("foodId") REFERENCES "foods"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
