# It needs to be node. Prisma still depends on something from node
# to generate the client.
FROM node:slim as base

# Install OpenSSL. Required for prisma to work.
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

RUN npm install -g bun@1.0.15

# Setup
COPY package.json bun.lockb ./
COPY /apps/taco/package.json /app/apps/taco/package.json
COPY /apps/website/package.json /app/apps/website/package.json
RUN bun install --ignore-scripts

COPY . .

RUN cd ./apps/taco && bunx prisma generate
EXPOSE 4000
ENTRYPOINT bun run dev --filter=taco-api