version: '3.9'

services:
  taco_api_dev:
    working_dir: /app
    build:
      context: ../../
      dockerfile: ./apps/taco/Dockerfile.dev
    environment:
      PORT: 4000

    ports:
      - 4000:4000
