# It needs to be node. Prisma still depends on something from node
# to generate the client.
FROM node:20-slim as base

# Install OpenSSL. Required for prisma to work.
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

RUN npm install -g bun@1.0.18 pnpm@8.12.1

# Setup
COPY . .
RUN pnpm install --ignore-scripts

EXPOSE 4000
ENTRYPOINT bun run dev --filter=taco-api