# It needs to be node. Prisma still depends on something from node
# to generate the client.
FROM node:20-slim as base

# Install OpenSSL. Required for prisma to work.
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

RUN npm install -g bun@1.0.20

# Setup
COPY package.json bun.lockb ./
COPY /apps/api/package.json /app/apps/api/package.json
COPY /apps/website/package.json /app/apps/website/package.json

RUN --mount=type=cache,id=buncache,target=/root/.bun/install/cache\
  bun install --frozen-lockfile --ignore-scripts

COPY . .

EXPOSE 4000
ENTRYPOINT bun run dev --filter=taco-api