name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v2

      - name: install bun
        run: pnpm install -g bun@1.0.18

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Necessary because it's being used in the code
      - name: Linting/Formating
        run: bun run lint:ci

      - name: Build
        run: bun run build
